# Generated by Django 4.2.5 on 2023-09-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('from_destination', models.CharField(max_length=100)),
                ('to_destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('date_and_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
